eureka:
  client:
    serviceUrl:
      defaultZone: http://152.136.69.7:8761/eureka/,http://140.143.36.160:8761/eureka/
  instance:
    prefer-ip-address: true
#开启路由 打开对Hystrix断路由
feign:
  hystrix:
    enabled: false
  client:
    config:
      CLOUD-PRODUCER:
        loggerLevel: full
      CLOUD-PRODUCER-MOVICES:
        loggerLevel: full
server:
  port: 8764
spring:
  application:
    name: cloud-feign
logging:
  level:
    com.cloud.client.indexClient: debug

