eureka:
  client:
    serviceUrl:
      defaultZone: http://152.136.69.7:8761/eureka/,http://140.143.36.160:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8765
spring:
  application:
    name: cloud-ribbon
