eureka:
  client:
    serviceUrl:
      defaultZone: http://152.136.69.7:8761/eureka/,http://140.143.36.160:8761/eureka/
server:
  port: 8001
spring:
  application:
    name: cloud-producer-movices
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://140.143.36.160:3306/cloud?useUnicode&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    default-auto-commit: false
    max-active: 100
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    max-idle: 25

management:
  security :
    enabled : false